version: "3.3"

services:
  quarkus:
    container_name: quarkus-java21
    image: pescador95/quarkus-java21:quarkus
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    env_file:
      - .env
    ports:
      - "3000:3000"
    networks:
      - internal-network

# ----- NETWORK -----
networks:
  internal-network:
    driver: bridge
